### ISSUE TITLE
PKCS11_enumerate_certs() returns cached results after login

### ISSUE THREAD

**Issue by dwmw2** [OpenSC/libp11#99] opened 2016-09-05 12:14 UTC
Some certificates are stored in tokens with the CKA_PRIVATE flag, so they aren't visible until you log in.

In OpenConnect I call `PKCS11_enumerate_certs()` to find the cert requested by the user. If no matching cert if found, and if only one token was found that matched the user's specification, then I log in to that token... and call `PKCS11_enumerate_certs()` again. This doesn't work because the second call to `PKCS11_enumerate_certs()` will immediately return a cached empty set of results, without asking the (now logged in) token again.

**Comment by mouse07410** [comment] 2016-09-05 14:47
> Some certificates are stored in tokens with the CKA_PRIVATE flag, so they aren't visible until you log in.

This is conceptually wrong. What tokens do that, and why the provisioner did not reconfigure this?

The whole idea is that one can use *public* information on the token *without* having to log in and provide the PIN, while *sensitive* operations (signing and decrypting or deriving) require PIN. This is used heavily in the scripts and tests, for example.

**Comment by dwmw2** [comment] 2016-09-05 16:02
With PKCS#11 as far as I can tell, you can basically assume that for *any* particular offence that is conceptually wrong, technically wrong, or morally wrong, there'll be someone out there who does it, for whom it works in their environment, and who expects it to work :)

For this particular case, it seems to be common enough that NSS considers its own internal token, which *does* reliably make certificates visible, to be a special case. It knows it needs to log in to other tokens before it concludes that a given certificate isn't present.

**Comment by mouse07410** [comment] 2016-09-05 16:52
Until recently SoftHSMv2 had public keys (and certificates?) CKA_PRIVATE by default - you needed to explicitly specify otherwise if you wanted the "sane" behavior. But a few weeks ago, they changed that to what the standard recommends, so now SoftHSMv2 default is CA_PRIVATE for private keys, and PUBLIC for the non-sensitive stuff.

I suspect that NSS does not care for certificates that are not accompanied by private keys, therefore it wants you to login anyway, so it can ascertain that if a fitting certificate is found - there is a private key with it.

I still don't know what your use case is (i.e., what *tokens* do not show their certificates unless logged in - NSS it not a token :), and what you propose to do to remedy the problem you're facing.

**Comment by dwmw2** [comment] 2016-09-05 20:13
Can you elucidate on *"what the standard recommends"*? Neither the [PKCS#11 base spec](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/pkcs11-base-v2.40.html) nor the [non-normative usage guidelines](http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html) seems to make that clear to me. It only says that the default value of `CKA_PRIVATE` is token-specific ([§4.4](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/pkcs11-base-v2.40-errata01-os-complete.html#_Toc441755768))

The SoftHSMv2 case you're thinking of is different — what was changed there recently was the case of `C_GenerateKeyPair()` in SoftHSMv2 without the `CKA_PRIVATE` attribute being explicitly specified in the `pPublicKeyTemplate` or `pPrivateKeyTemplate` arguments.

What we're talking about here though is `CKO_CERTIFICATE` objects, which are always going to be created with an explicit `C_CreateObject()` call.

We're not left to the token-specific defaults there. It seems that `p11tool` still does create `CKO_CERTIFICATE` objects with the `CKA_PRIVATE` attribute by default, unless explicitly asked not to with the `--no-mark-private` argument. Perhaps we can hassle @nmav to fix that. But still, with software only just fixed to get this "right" it'll be years before we see it deployed to some of the less well-maintained distributions like Ubuntu. 

And that's not even taking into consideration all the random hardware devices out there with badly-maintained PKCS#11 libraries of their own, and their own baroque deployment processes.

As for "use case"... I don't have a specific use case in mind. I'm writing software that I expect to be usable by *everyone*. I need to support *every* use case, even the ones which don't necessarily meet our ideals.

So... we have a behaviour *(certs with `CKA_PRIVATE`)* which is prevalent in existing deployed software, which works with GnuTLS and NSS client because they explicitly expect it, and which I can't actually see it being non-recommended in the spec even when I'm *looking* for it. And in fact I could have sworn this *used* to work with libp11 when I first wrote this code.

So yes, that's *one* of the use cases I think I need to support. And when I say *"I need to support"* this is me getting my own ducks in a row before I go and change the Fedora [packaging guidelines]( https://fedoraproject.org/wiki/Packaging:SSLCertificateHandling) to set expectations that *all* software packaged for the distribution should cope.

> Also, a "simple" fix by just re-reading the objects from the token upon login would break the ability to sign (because SIGN operation must be immediately proceeded by PIN VERIFY according to the standard SP 800-73), so that's not an option.

That's a PIV standard, not PKCS#11, so that's an internal implementation detail for OpenSC to worry about, surely? If you have a key which needs the PIN before every signing operation, doesn't that translate to the `CKA_ALWAYS_AUTHENTICATE` attribute in PKCS#11? Otherwise.. what exactly are you saying? That when I'm loading the cert and the key from PKCS#11 I *have* to load the cert first, because searching for the cert will stop the key from being usable?

**Comment by mouse07410** [comment] 2016-09-05 22:58
>  Neither the PKCS#11 base spec nor the non-normative usage guidelines seems to make that clear to me. It only says that the default value of CKA_PRIVATE is token-specific (§4.4)

On the contrary - it clearly says that CKA_PRIVATE should be TRUE for private, and FALSE for public objects. The very paragraph that you referred to (4.4). 

> It seems that p11tool still does create CKO_CERTIFICATE objects with the CKA_PRIVATE attribute by default, **unless explicitly asked not to with the `--no-mark-private` argument**. 

So I contend that the problem is improperly provisioned tokens, created with wrong parameters - bad defaults in `p11tool` probably a contributing factor.

> Perhaps we can hassle @nmav to fix that. 

I'm sure we can, and should. After all, @nmav offered the PR to SoftHSMv2 that was accepted, fixing the problem I mentioned - having public keys marked as CKO_PRIVATE.

Nikos, could you comment please?

> But still, with software only just fixed to get this "right" it'll be years before we see it deployed to some of the less well-maintained distributions like Ubuntu.

Well, I sympathize, but that's how bug fixes get propagated. If you feel urgency - perhaps you can communicate your concerns to Ubuntu maintainers.

> ...we have a behaviour (certs with CKA_PRIVATE) which is prevalent in existing deployed software...

I'd say this behavior is rare. None of my tokens exhibits it. OpenSC does not do it. Commercial CMS (Card Management Solutions) don't exhibit it. AFAIK, libp11 does not do it. So what software do you have in mind, besides p11tool with wrong input parameters? Could you list those guilty packages, please?

> ...which works with GnuTLS and NSS client because they explicitly expect it...

I don't know what you mean, but GnuTLS (or specifically, `p11tool`) gets certificates from a locked token perfectly fine:
```
$ p11tool --list-all-certs "pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=a0f5.....;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29"
Object 0:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=a0f5.....;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%01;object=Certificate%20for%20PIV%20Authentication;type=cert
	Type: X.509 Certificate
	Label: Certificate for PIV Authentication
	ID: 01

Object 1:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=a0f5.....;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%02;object=Certificate%20for%20Digital%20Signature;type=cert
	Type: X.509 Certificate
	Label: Certificate for Digital Signature
	ID: 02

Object 2:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=a0f5.....;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%03;object=Certificate%20for%20Key%20Management;type=cert
	Type: X.509 Certificate
	Label: Certificate for Key Management
	ID: 03

Object 3:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=a0f.....;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%04;object=Certificate%20for%20Card%20Authentication;type=cert
	Type: X.509 Certificate
	Label: Certificate for Card Authentication
	ID: 04

$ 
```

> ..., and which I can't actually see it being non-recommended in the spec even when I'm looking for it.

The very paragraph you referred to clearly said for what type of objects CKO_PRIVATE should be set to TRUE. Nobody in their right mind would call a certificate a "private object", when the classificators are "private" and "public", and the objects to classify are "private key", "public key", "certificate" (aka "signed public key").

> If you have a key which needs the PIN before every signing operation, doesn't that translate to the `CKA_ALWAYS_AUTHENTICATE` attribute in PKCS#11?

Yes, correct.

> ...what exactly are you saying? 

I'm saying that the software I'm aware of (various Tokend packages, Windows minidriver,  ActivClient) first load certificates from the token (I assume they assume that for each certificate the token got to have a corresponding private key). Then if an operation with a private key is requested, they prompt the user for his PIN, and perform the operation. 

> That when I'm loading the cert and the key from PKCS#11 I have to load the cert first, because searching for the cert will stop the key from being usable?

I don't know - I find it possible. I've never experimented with that part.

**Comment by dengert** [comment] 2016-09-06 01:21
In regards to discussion between @mouse and @dwmw2 about PIV:

Early versions of NIST 800-73 had the certificates as private and the card required the PIN. I actually have a GemSafe PIV card from 2006 that requires the PIN to read the certificate.  **Everyone** (Including Microsoft as they were writing their on PIV driver) complained and NIST 800-73-2 changed it so all certs were public.  This is not to say that there may still be some reasons to have a card with private certificate.

The PIV card when using the signing key, requires no card commands between the VERIFY PIN command and the  GENERAL AUTHENTICATE command that does a crypto operation. Code was added to OpenSC PKCS#11 and to NSS to support CKA_ALWAYS_AUTHENTICATE because of the PIV sign key.

The PIV card could have a key, without a certificate, but it would not be usable by any common middleware. To use the key one would have to know what type of key and the size. NIST 800-78 defines  the "Algorithm Identifier", and there are only 4 (to keep it simple) in current use: (06)RSA 1024, (07)RSA 2048, (11)ECC Curve P-256 and (14)ECC Curve P-384.  In normal use including the PIV driver, the "Algorithm Identifier" is derived from the public key in the certificate.  Without a certificate, one could write code to try all 4 "Algorithm Identifier" and find one that worked.

**Comment by mouse07410** [comment] 2016-09-06 01:56
> Early versions of NIST 800-73 had the certificates as private and the card required the PIN. I actually have a GemSafe PIV card from 2006 that requires the PIN to read the certificate.

Wow. CAC in 2009 sure did not require PIN to read its certificates.

I wonder, if PR #100 doesn't break the current PIV functionality, perhaps it would be harmless?

**Comment by mtrojnar** [comment] 2016-09-06 05:06
Merged.

**Closed by mtrojnar** 2016-09-06 05:06 UTC

**Comment by nmav** [comment] 2016-09-06 07:08
>>    Perhaps we can hassle @nmav to fix that.
> I'm sure we can, and should. After all, @nmav offered the PR to SoftHSMv2 that was accepted, fixing > the problem I mentioned - having public keys marked as CKO_PRIVATE.

I didn't know this, thanks for bringing it up.
https://gitlab.com/gnutls/gnutls/merge_requests/63

**Comment by nmav** [comment] 2016-09-06 07:11
> Early versions of NIST 800-73 had the certificates as private and the card required the PIN. I actually have a GemSafe PIV card from 2006 that requires the PIN to read the certificate. Everyone (Including Microsoft as they were writing their on PIV driver) complained and NIST 800-73-2 changed it so all certs were public. This is not to say that there may still be some reasons to have a card with private certificate.

The same was with the Belgian ID cards (which were also smart cards). They had the certificate marked as private.

**Comment by dwmw2** [comment] 2016-09-06 09:39
Technically this is resolved and now working (thanks).

But @mouse07410 appears to be arguing vehemently against supporting supporting certificates which have the `CKA_PRIVATE` flag set, so I'll just respond to that to hopefully clear it up...

> The very paragraph you referred to clearly said for what type of objects CKO_PRIVATE should be set to TRUE. Nobody in their right mind would call a certificate a "private object", when the classificators are "private" and "public", and the objects to classify are "private key", "public key", "certificate" (aka "signed public key").

No. The terms *"public object"* and *"private object"* have a specific meaning in PKCS#11, as set out in the specification. Different types of (user/SO, RO/RW) sessions can do different things with public vs. private objects, there can be different storage space allocated for them and they are accounted separately in the `CK_TOKEN_INFO`.

Nowhere is it stated that all objects with `CKA_CLASS==CKO_CERTIFICATE` shall be *"public objects"* and thus have `CKA_PRIVATE` set to `CK_FALSE`. And nowhere is it stated that all objects with `CKA_CLASS==CKO_PRIVATE_KEY` shall be *"private objects"* and have `CKA_PRIVATE` set to `CK_TRUE`. Quite the contrary, in fact — the default is explicitly said to be token-specific. And if the public/private state *were* dictated by the `CKA_CLASS` value, then the `CKA_PRIVATE` attribute itself would be redundant and shouldn't exist in the spec at all. Or at least it shouldn't be valid for those classes of object.

> I'm saying that the software I'm aware of (various Tokend packages, Windows minidriver, ActivClient) first load certificates from the token (I assume they assume that for each certificate the token got to have a corresponding private key). Then if an operation with a private key is requested, they prompt the user for his PIN, and perform the operation. 

Fair enough. But the software *I'm* aware of (NSS, GnuTLS) does cope with certificate objects having the `CKA_PRIVATE` attribute, and will log in to the token before concluding that a given certificate they are searching for does not exist.

So if I use the token in this test case and build, say, `curl` with either GnuTLS or NSS as its crypto library, then I can expect this command to work:
`$ curl -E 'pkcs11:token=openconnect-test;id=%01' …`
If I build `curl` against OpenSSL+libp11, however, I believe it wouldn't. At least, not until my patch that got merged in PR #100.

> So I contend that the problem is improperly provisioned tokens, created with wrong parameters - bad defaults in p11tool probably a contributing factor.

I'm vaguely sympathetic to that viewpoint — but even if it's true, that doesn't mean we shouldn't support them. You might consider it *"improper"* — and with good reason — but it still happens. There exist PKCS#11 modules and tokens with all manner of misbehaviours, and at least this one is explicitly *permitted* by the specification; unlike others we have to work around :)

So sure... go ahead and recommend to the PKCS#11 WG that the language be changed, and setting `CKA_PRIVATE=CK_FALSE` on *all* `CKO_CERTIFICATE` objects should be made mandatory. Or if not mandatory, at *least* a recommendation in the Usage Guide.

But I'm not sure they'll do it. After all, from the pure security point of view what's the *point* in certificates being stored in the token without `CKA_PRIVATE`? They might as well be stored in software. Sure it's *convenient* to have them physically mobile with the key in the token, but that's just software convenience... since when do hardware designs take that into account?

And some people might *want* the certificate to be considered private. Again from the security point of view, what's the point in it *not* being private, if you're going to have to log in to the token to use the associated key anyway? If you have a device whose hardware random number generator might hypothetically at some point in the future turn out to have been substandard, why allow an attacker to read the certificate without a PIN, to let them do a brute force attack and guess the key? Why *not* set `CKA_PRIVATE` on the certificate too?

Even though I work for Intel I don't *normally* wear the company-issue tinfoil hat, so I concede I'm cringing a bit as a write the above paragraph. I'm not *advocating* for certificates to be stored with the `CKA_PRIVATE` attribute... just that it's a use case we do need to support, and we can't just declare it "wrong" out of hand.

**Comment by dengert** [comment] 2016-09-06 13:30
The 2006 card was a development card based on the early standard.
    They were never in general use. I brought it up to show some of the
    history and why everyone complained. But there could still be tokens
    that don't allow any object to be read without a PIN. if stolen dose
    not reveal any information, and does not have any external making
    either.  For example something a spy might use. If captured, the
    token dose not reveal any information, and does not have any
    external making either.
    
    On 9/5/2016 8:56 PM, Mouse wrote:
    
    
      
        Early versions of NIST 800-73 had the certificates as private
          and the card required the PIN. I actually have a GemSafe PIV
          card from 2006 that requires the PIN to read the certificate.
      
      Wow. CAC in 2009 sure did not require PIN to read its
        certificates.
      I wonder, if PR #100
        doesn't break the current PIV functionality, perhaps it would be
        harmless?
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/libp11","title":"OpenSC/libp11","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/libp11"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mouse07410 in #99: \u003e Early versions of NIST 800-73 had the certificates as private and the card required the PIN. I actually have a GemSafe PIV card from 2006 that requires the PIN to read the certificate.\r\n\r\nWow. CAC in 2009 sure did not require PIN to read its certificates.\r\n\r\nI wonder, if PR #100 doesn't break the current PIV functionality, perhaps it would be harmless?"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/libp11/issues/99#issuecomment-244832386"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mouse07410** [comment] 2016-09-07 01:23
> The terms "public object" and "private object" have a specific meaning in PKCS#11, as set out in the specification.

These terms occur in the document exactly 8 and 6 times correspondingly. Could you please point me at what specific meaning your statement refers?

Also, while the document does not explicitly state that a "public key" should normally be a "pubic object", this sounds very much like argument about what's the exact definition of "was" and "alone". Thankfully, we are not lawyers (at least I am not :), and most people (especially those familiar with the concepts of Public Key Crypto) wouldn't have to think hard to figure which object should be which.

I'm dealing with smart cards since 2009, and so far have never encountered any where these definitions would depart from the common sense. So it appears that after the first PKCS#11 definition fiasco (as @dengert described), they listened up and wizened up, and the problem seemed rectified then and there. 

As long as we don't bend over backwards to accommodate those (in my opinion) broken tokens, endangering correct functionality of the "normal" ones - I don't mind supporting such weird cases. But I cannot and would not name them anything other than this - weird cases of broken tokens.

**Comment by dengert** [comment] 2016-09-07 02:39
@mouse You are mis-quoting what I said. I never said: "PKCS#11 definition fiasco (as @dengert described)". I was referring to early drafts of NIST 800-73 where reading the certs required verification of the PIN. NIST never specified a PKCS#11 interface to the PIV cards.  To early PIV developers, it was obvious that a PKCS#11 interface would make using the cards easier for login or use with SSL client authentication. And it would make it much easier if  the certificates could be read before entering the PIN. 

PKCS#11 v 2.01, 1997 is the earliest version I have, and only on paper. It defines Common Object Attributes. CKA_PRIVATE is one of them. "Default value is token specific and may depend on the values of other attributes of the object." 

I never used the term "fiasco".  It was a usability issue. @nmav pointed out Belgian ID cards had certificates marked as private. I would not call that weird.

**Comment by mouse07410** [comment] 2016-09-07 02:56
> You are mis-quoting what I said. I never said: "PKCS#11 definition fiasco"

My apologies - that's what I said. You described how the first PKCS#11 standard required having certificates private, and how it caused a rebellion among **all** of the users. I (not you) chose to call that experience "fiasco", because that's the only polite term that comes to mind when a standard requires something that nobody agrees with. 

I wasn't clear enough - I meant to apply "fiasco" to making certificates CKA_PRIVATE, and not to the rest of the standard (which I use happily, among others :).

> And it would make it much easier if the certificates could be read before entering the PIN.

And determining if this is the right token. While large organizations usually issue just one token to a person, there are cases when a person has more than one token, and needs to decide which token to use (again, in some cases they're like CAC or PIV - so looking at the name or photo is enough, in other cases they're like YubiKeys, SmartCardHSM, or others - in which case being able to see what kind of certs are stored on this token helps).

> @nmav pointed out Belgian ID cards had certificates marked as private. I would not call that weird.

I realize that, and I'm sure Belgian government would agree with you rather than me in this case. Still, my opinion on this is not swayed. ;-)

**Comment by dwmw2** [comment] 2016-09-07 07:41
@mouse07410 You are confusing the two standards. PIV is one specific hardware token, while PKCS#11 is the generic API which supports *all* kinds of hardware and software crypto "devices" and must represent a superset of their capabilities and requirements.

The PKCS#11 API supports **much** more than just PIV. Some tokens *do* default to marking certificates with `CKA_PRIVATE`, as the PKCS#11 spec permits. PIV *used* to do so, as @dengert described, but doesn't any more. Others still do. And some tools still do import certificates with the `CKA_PRIVATE` attribute explicitly. It is a valid use case which an application should support.

As for what the standard says...
> These terms occur in the document exactly 8 and 6 times correspondingly. Could you please point me at what specific meaning your statement refers?

Let's look at them. The spec says of public objects...
 - That the `ulTotalPublicMemory` and `ulFreePublicMemory` fields in `CK_TOKEN_INFO` indicate the amount of memory available for storage of such objects.
 - That  `CKA_PRIVATE` being false indicates that an object is a public object.
 - That only public objects can be created by `C_CreateObject()` or `C_CopyObject()`, or deleted by `C_DestroyObject()` unless the normal user is logged in.
 
...and of private objects...
 - That the `ulTotalPrivateMemory` and `ulFreePrivateMemory` fields in `CK_TOKEN_INFO` indicate the amount of memory available for storage of such objects.
 - That `CKA_PRIVATE` being true indicates that an object is a private object.
 - That *"a private object cannot be created on a token unless the session attempting to create it is logged in as the normal user"*.
 - That *"when `C_Logout` successfully executes, any of the application’s handles to private objects become invalid"*.
 - That *"if an application deletes (say) a private object of size S, it might be reasonable to assume that the `ulFreePrivateMemory` field of the token’s `CK_TOKEN_INFO` structure increases by approximately S."*
 - That *"an object search in an “R/W Public Session” will not find any private objects"*.

That is what the spec has to say about public and private objects; that is the limit of what those terms mean. There's nothing to support the assertion that certificate objects **MUST** be public objects, and private keys **MUST** be private objects.

The Usage Guide also says ([§3.1](http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html#_Toc406759999)):
*"1.       Access to private objects on the token, and possibly to cryptographic functions and/or certificates on the token as well, requires a PIN. Thus, possessing the cryptographic device that implements the token may not be sufficient to use it; the PIN may also be needed."*

It is quite clear that accessing even the *certificate* might require a PIN. Both in the PKCS#11 documentation, and in the real-life use cases which have been described to you.

**Comment by dwmw2** [comment] 2016-09-07 07:42
And actually.... an object without `CKA_PRIVATE` can be deleted by a `C_DeleteObject()` call in a public R/W session... that is, without the PIN being entered? Am I reading that right? Perhaps I want to make *all* my certificates `CKA_PRIVATE` to prevent them being deleted?

**Comment by nmav** [comment] 2016-09-07 08:28
> And actually.... an object without CKA_PRIVATE can be deleted by a C_DestroyObject() call in a public R/W session... that is, without the PIN being entered? Am I reading that right? Perhaps I want to make all my certificates CKA_PRIVATE to prevent them being deleted?

I don't know on that particular, but most opensc smart cards you can completely erase without any kind of access control. That's why we introduced [SC access only on console in fedora](https://access.redhat.com/blogs/766093/posts/1976313).

**Comment by dengert** [comment] 2016-09-07 12:43
@mouse again you are misstating my position when you said: "You described how the first PKCS#11 standard required having certificates private, and how it caused a rebellion among all of the users."

The first PKCS#11 standards, never required  having certificates private. It says the CKA_PRIVATE depends upon the token. 

What I did described was early NIST 800-73 PIV standards required the card to enforced use of the PIN to access certificates. Many "complained" (not "a rebellion") about NIST 800-73 and I assume Microsoft did too, as having to use the PIN to read the certificates did not fit with their smart card login model. Microsoft does not use PKCS#11. Even the OpenSC minidriver does not use PKCS#11 it uses the OpenSC PKCS#15 routines.  

In 2004 I took upon the task of providing a PKCS#11 interface to the PIV card, and the way I did that was to use OpenSC  and write card-piv.c and pkcs15-piv.c  In order to follow the early NIST 800-73 standard (It may have been a draft, but card vendors were providing test cards for it) of certs requiring the PIN, translates into  returning CKA_PRIVATE=TRUE as an attribute. 

In regards to certs and pubkey should had  CKA_PRIVATE=FALSE and private key should have
CKA_PRIVATE=TRUE. PKCS#11 says CKA_PRIVATE depends  upon the token. Have a look at the pkcs15-piv.c and the "CARD AUTH key" You will note that the SC_PKCS15_CO_FLAG_PRIVATE is not set for this one private key. When translated into PKCS#11 this private key has CKA_PRIVATE=FALSE
pkcs11-tool -O with oit the -l will list this key, because it is  CKA_PRIVATE=FALSE

"we don't bend over backwards to accommodate" these tokens, because PKCS#11 is a robust standard that can accommodate any object having CKA_PRIVATE = {TRUE | FALSE}

**Comment by dengert** [comment] 2016-09-07 20:46
Comment on: "an object without CKA_PRIVATE can be deleted by a C_DestroyObject()", "but most opensc smart cards you can completely erase without any kind of access control" and 
[ SC access only on console in fedora](https://access.redhat.com/blogs/766093/posts/1976313)

Good see someone finally addressing SC Access control, especially once the PIN is presented to the card other processes on machine could send crypto commands to the card, which in my option is much more a problem then completely erasing the card.  This requires some long running process to have sent the PIN, and no other process doing a card_reset, that resets the PIN state on the card. 
The opensc.conf has some features to restrict access or relax access control:  transaction_end_action= and disconnect_action=.  These can be either too restrictive on the user or too lax. Looks like having SC Access control makes for a better single-signon experience. 

The deletion of objects on the card really depends on the card. Government or organization issued cards don't allow the user to create modify or destroy objects. The cards are provisioned by a Card Management System and usually have some 3DES or AES key for each card known only to the CMS.  So even if  PKCS#11 is used to access the card in normal usage modes, the PKCS#11 can not cause the card to be changed. 

On the other hand there are cards designed for the end user to use as they see fit and using just the PIN may allow for the objects to be modified or deleted.  Its the user's card. 

There are are card vendors that provide separate tools that allow for a user card to be erased. The commands to the card are most likely not implemented in the PKCS#11 software.

**Comment by mouse07410** [comment] 2016-09-08 21:07
OK, you guys are all correct, and since the requested change did not affect negatively the current PIV functionality, I'm OK with it. It's been merged and tested - all is fine.

Thanks for everybody's effort, and I'm sure this issue can be closed now. @dwmw2?

**Comment by dwmw2** [comment] 2016-09-08 21:16
I think it's already closed. I just wanted to shout at you some more... :)

**Comment by mouse07410** [comment] 2016-09-09 00:09
> I think it's already closed. I just wanted to shout at you some more... :)

That's fine, but why didn't you get in line? :-)
