### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by ebenwar** [OpenSC/libp11#403] opened 2021-05-06 13:55 UTC
I noticed the new feature CMD_RE_ENUMERATE, commit [add re-numeration of slots as engine ctrl command ](https://github.com/OpenSC/libp11/commit/bfcd96a58ad3535a68a3b599a11e9f9f2e568e59) and I think it may result in memory leaks.

PKCS11_enumerate_slots is called in

`static  int ctx_enumerate_slots(ENGINE_CTX *ctx, PKCS11_CTX *pkcs11_ctx)`

to read the current slot list and count from the hsm which is then assigned to the passed ENGINE_CTX ctx.
if `ctx->slots` has been assigned in a previous call memory is leaked.
Note: I guess `PKCS11_release_all_slots` can't be called at this point since the old list might be in use by another thread.

**Comment by dengert** [comment] 2021-05-25 16:42
As follow on to #407 
The `C_GetSlotList` depends on the caller providing the memory for the list.  The list contains a list of SlotIDs - 
`typedef CK_ULONG CK_SLOT_ID;` So  the old ctx->slots could be freed. So the memory leak could be fixed. 
The use of ctx->slots should be protected by a mutex, and the index into the slot array may change as the list of slots changes, but active SLOT_IDs should be in the old and new list. 
The CK_SLOT_ID are assigned by the PKCS11 module that is responsible to keep them unique.

**Comment by ebenwar** [comment] 2021-05-26 07:44
I don't think a mutex is needed since ctx_enumerate_slots is only called by openssl, from ENGINE_ctrl_cmd_string, with the global engine lock held.
But I don't think the old list could be freed since it might be in use by another thread.
Maybe realloc, as in pkcs11_enumerate_keys, could be used?

**Comment by dengert** [comment] 2021-05-26 12:30
@fabled  after implementing session pooling, maybe you have some comments on this issue and #407 

`realloc` can change the pointer, so that will not solve any issues with other threads using the pointer. 

I was suggesting a mutex for the use of the pointer. That will require looking at all the usage of  `ctx->slots`. They all appear to be in `eng_back.c`, but `ctx->slot_list` is passed to some other routines. 

- `ctx_enumerate_slots` sets `ctx->slot_list` by calling `PKCS11_enumerate_slots` 

- `ctx_init_libp11_unlocked`  calls `ctx_enumerate_slots`  (Strange name, because `ctx_init_libp11` calls `ctx_init_libp11_unlocked` while holding the `ctx->lock`.)

- `ctx_init_libp11` test it. 
- `ctx_load_cert`  uses it  to search for tokens that have matching certificates

- `ctx_finish`  calls  `PKCS11_release_all_slots` and justs sets `ctx->slot_list = NULL;` 
- `pkcs11_release_all_slots` calls  `OPENSSL_free(slots);`  i.e. `ctx->slot_list`
- `pkcs11_release_slot`  uses individual slotIDs  and also calls `C_CloseAllSessions` which causes PKCS11 module to close ALL sessions to the token and not just the sessions for this `PKCS11_CTX *ctx`   this is first problem in #407 @fabled , should this be changed to close only the sessions used by this `PKCS11_CTX *ctx`? Will it cause a problem with session pooling?

I may have missed some other cases. I do not have a good way to test/debug the many combinations of using multiple `PKCS11_CTX *ctx`.

**Comment by fabled** [comment] 2021-05-26 13:20
> * `pkcs11_release_slot`  uses individual slotIDs  and also calls `C_CloseAllSessions` which causes PKCS11 module to close ALL sessions to the token and not just the sessions for this `PKCS11_CTX *ctx`   this is first problem in #407 @fabled , should this be changed to close only the sessions used by this `PKCS11_CTX *ctx`? Will it cause a problem with session pooling?

This should be ok. The code also earlier was calling `C_CloseAllSessions` so I did not change it. I think the earlier logic was to make sure no one is holding active sessions, so that the slot/token logged-in state would be reset. Just closing the specific sessions opened is just fine. But I suspect some logic changes might be needed to the logged-in state tracking also.

I think the logged-in state handling is especially tricky in #407 because all sessions from same process will share the logged-in state.

What comes to the `slot_list` handling in general, this is an issue I recognized. Similar issue exists with the cached objects when that list gets reallocated (the internal pointers are moved, but it might causes problems if another thread is working on that object concurrently). I'm currently thinking what to do with that, and seems there's no nice solutions. Fundamentally the PKCS11_* API was designed for single-threaded single-context-instance use, and making it fully multi threaded safe afterwards is non-trivial. The work I did was mostly limited to the openssl engine usage pattern only.

**Comment by ebenwar** [comment] 2021-05-26 13:23
I still don't think a lock is needed
`ctx_init_libp11_unlocked ` is only called by `ctx_init_libp11`

`ctx_init_libp11 `is called from `ctx_load_pub/priv_key` and `ctx_ctrl_load_cert`, all 3 are called from openssl via the ENGINE api functions

1. `ENGINE_ctrl`
2. `ENGINE_load_private_key`
3. `ENGINE_load_public_key`
All 3 holds the `global_engine_lock`

`ctx_finish `is never called, at least for me, due to the EVP_PKEY instance in PKCS11_key_st holds a structural reference to the `ENGINE` making `EVP_PKEY_free `never reach 0 which in turns never makes `EVP_PKEY_free` call ossl internal function `EVP_PKEY_free_it` making `ENGINE_finish(x->engine)` never to be called.
But if it would be called it also is only called by opensll with `global_engine_lock` held

I have 2 patches which makes it work for me

A)
 `PKCS11_release_all_slots`  and `pkcs11_open_session` only closes sessions known to the PKCS11_SLOT instance, the pool
B) 
1. moved `EVP_PKEY *evp_key` in `struct PKCS11_key_st` to a `void *key` in `struct pkcs11_key_private`
2. the `void *key` is then either a `EC_KEY` or a `RSA` instance created once in `oops->get_evp_key` that returns a `EVP_PKEY` instance with only 1 as structural reference counter
3. Gives when the last structural reference to the `ENGINE` is removed may `ENGINE_finish` be called even if the engine has returned different keys

**Comment by dengert** [comment] 2021-05-26 15:17
@fabled Having running into login state issues with cards with multiple applets on a card and multiple processes running each using a different applet on the card, there will be times when the login state gets reset.   I agree the login state is tricky, as that is kept by the token. And since this interference can come from other processes, Libp11 needs to handle loss of login state. 

It sounds like @ebenwar has a replacement for the C_CloseAllSessions  problem. 
Can you submit this as a PR? 

@fabled with regards to the slot_list contents, these are handles created by the PKCXS11 module. When `C_GetSlotList` is called, the pkcs11 module will return a new list of these handles, plus new slots found minus slots which are no longer are valid. Since tokens can be removed, an application has to handle return codes like: CKR_TOKEN_NOT_PRESENT, CKR_DEVICE_REMOVED,  CKR_OBJECT_HANDLE_INVALID, CKR_KEY_HANDLE_INVALID etc. i.e. the PKCS11 module is setup to check handles are still valid when they are used. 

PKCS11 does not return pointers to objects. So the statement: " (the internal pointers are moved, but it might causes problems if another thread is working on that object concurrently)." This would be an issue with libp11 internally. I don't think we have that problem, if the libp11 code handles CKR_* properly. 

Note that the calling of `PKCS11_enumerate_slots` by the application or by the engine  internally is already replacing the ctc->slot_list pointer. That is why I was asking about a mutex for it, or use the ctx->mutex to protect  it.

**Comment by fabled** [comment] 2021-05-26 15:23
> PKCS11 does not return pointers to objects. So the statement: " (the internal pointers are moved, but it might causes problems if another thread is working on that object concurrently)." This would be an issue with libp11 internally. I don't think we have that problem, if the libp11 code handles CKR_* properly.
> 
> Note that the calling of `PKCS11_enumerate_slots` by the application or by the engine internally is already replacing the ctc->slot_list pointer. That is why I was asking about a mutex for it, or use the ctx->mutex to protect it.

Did not read this part of the code or intend to comment this. But sounds like a feasible approach.

**Comment by ebenwar** [comment] 2021-05-27 09:45
PR, sorry but basically
1) pkcs11_init_slot initialize the pool with 0
2) pkcs11_get_session when a session leaves the pool, set the pool slot to 0
3) in pkcs11_open_session and pkcs11_release_slot, iterate over the pool and close known sessions

**Comment by dengert** [comment] 2021-05-27 11:34
If not a PR, how about a diff. 
It wont get fixed in the source until someone  submits a PR. Preferably someone who has the problem and can test it.
A PR can be generated form a diff of your changes.

**Comment by ebenwar** [comment] 2021-05-28 07:40
Sorry I'm not allowed to publish any code in any format

**Comment by dengert** [comment] 2021-05-28 12:26
Sorry to hear that you are "not allowed to publish any code in any format".
You may want to speak to your management about this policy as it is to your advantage to provide fixes for problems you have found in Open Source projects:
- You don't have to patch every new version.
- You  don't have to redistribute the modified code with your product.
- It makes it much easier to live up to the Licenses that cover this software.

If you will note that every source file has License information and copyrights. 
[GNU Lesser General Public License version 2.1 ((LGPLv2.1)](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html) or 
[OpenSSL license (the "License")](https://www.openssl.org/source/license.html) Historically libp11 and engine were two separate projects, but are now in one project. The PKCS11 part was covered by the LGPL, and the engine by the OpenSSL license.

**Comment by fabled** [comment] 2021-05-31 07:53
> PKCS11 does not return pointers to objects. So the statement: " (the internal pointers are moved, but it might causes problems if another thread is working on that object concurrently)." This would be an issue with libp11 internally. I don't think we have that problem, if the libp11 code handles CKR_* properly.

Actually this is a problem. PKCS#11 deals with the handles only, and is safe. However, libp11 uses the `PKCS11_SLOT*`. And unfortunately, the `pkcs11_enumerate_slots` re-allocates them on every call. This means the function is unsafe as it causes the slots structures to be reallocated and the pointers will change. Effectively it will invalidate all old structs, and the if some other threads are using them, they will crash. Similar is true for public/private key and certificates objects (`PKCS11_KEY*` and `PKCS11_CERT*` ). The API is designed so that it assumes the library to allocate the variables linearly, and cache them over calls. This design is clearly for single threaded use, and causes problems. We may have to redesign the libp11 API on this part to fix the issue (likely keep the current API in deprecated/emulated form). There are also other issues in the cert/key handling, and I will create next another ticket about that to track it.

**Comment by fabled** [comment] 2021-05-31 07:59
>  However, libp11 uses the `PKCS11_SLOT*`. And unfortunately, the `pkcs11_enumerate_slots` re-allocates them on every call.

Oh, this seems to be different from how certificates/keys are cached. It's a caller provided list. While this can be worked around by each thread maintaining it's own list, it's slightly inefficient and difference from how the key/cert cache works. Or perhaps it's as designed, but would need additional documentation.

**Closed** 2021-06-27 14:11 UTC
