### ISSUE TITLE
Test suite fails in 0.4.11 with openssl 1.0.2k (in Amazon Linux 2)

### ISSUE THREAD

**Issue by ozbenh** [OpenSC/libp11#404] opened 2021-05-07 02:18 UTC
I see these failures: 

```
FAIL: pkcs11-uri-without-token.softhsm
FAIL: search-all-matching-tokens.softhsm

```

It also fails with Fedora's 0.4.10. If I start from 0.4.10 and add the patches that Fedora carries, this one is the starting point:

openssl-pkcs11-0.4.10-search-objects-in-all-matching-tokens.patch

Which boils down to these commits:

712e869189610f900ebf8c50090e228167b6bf8f and
85a91f4502d48371df0d392d19cecfbced2388c0

I've attached the test suite log for the failing tests.
[test-suite.log](https://github.com/OpenSC/libp11/files/6438605/test-suite.log)

**Comment by mouse07410** [comment] 2021-05-07 02:39
These tests fail for me consistently on MacOS for the last several OS versions, when compiled against OpenSSL-3.0.

**Comment by ansasaki** [comment] 2021-05-12 17:02
@ozbenh Hi, could you please inform the openssl and softhsm versions you are using?

I noticed a curious thing in your logs:
```
Signature Verified Successfully
Failed to verify signature using PKCS#11 URI pkcs11:object=server-key;type=public;pin-value=1234
```
Which suggests that perhaps ``openssl pkeyutl -verify`` is not returning zero when it successfully verifies the signature.

**Comment by ansasaki** [comment] 2021-05-12 17:28
@ozbenh Nevermind my question about the version, I saw the title now. I'll investigate a bit if I can find the reason for the failure.

**Comment by ansasaki** [comment] 2021-05-12 19:08
@ozbenh I tested on a amazon linux container and confirmed that the `openssl pkeyutl -verify` always returns 1, regardless of being successful or not. Follows part of my interactive test:
```
bash-4.2# p11tool --list-all --login pkcs11:token=softhsm
Token 'softhsm' with URL 'pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=3b356d47b0ebe5da;token=softhsm' requires user PIN
Enter PIN: 
Object 0:
	URL: pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=3b356d47b0ebe5da;token=softhsm;id=%87%EF%5E%7C%B1%BE%1B%2A%7D%A5%B5%65%9C%BC%6F%B8%80%5E%DE%5D;object=test;type=private
	Type: Private key
	Label: test
	Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_SENSITIVE; 
	ID: 87:ef:5e:7c:b1:be:1b:2a:7d:a5:b5:65:9c:bc:6f:b8:80:5e:de:5d

Object 1:
	URL: pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=3b356d47b0ebe5da;token=softhsm;id=%08%07%EF%5E%7C%B1%BE%1B%2A%7D%A5%B5%65%9C%BC%6F%B8%80%5E%DE%5D;object=test;type=public
	Type: Public key
	Label: test
	Flags: CKA_WRAP/UNWRAP; 
	ID: 08:07:ef:5e:7c:b1:be:1b:2a:7d:a5:b5:65:9c:bc:6f:b8:80:5e:de:5d

Object 2:
	URL: pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=3b356d47b0ebe5da;token=softhsm;id=%87%EF%5E%7C%B1%BE%1B%2A%7D%A5%B5%65%9C%BC%6F%B8%80%5E%DE%5D;object=test;type=cert
	Type: X.509 Certificate
	Label: test
	ID: 87:ef:5e:7c:b1:be:1b:2a:7d:a5:b5:65:9c:bc:6f:b8:80:5e:de:5d

bash-4.2# openssl pkeyutl -engine pkcs11 -keyform engine -inkey "pkcs11:object=test;type=private" -in in.txt -sign -out sig.bin
engine "pkcs11" set.
Found uninitialized token
Found uninitialized token
Enter PKCS#11 token PIN for softhsm:
bash-4.2# openssl pkeyutl -engine pkcs11 -verify -sigfile sig.bin -in in.txt -pubin -keyform engine -inkey "pkcs11:token=softhsm;object=test;type=public;id=%08%07%EF%5E%7C%B1%BE%1B%2A%7D%A5%B5%65%9C%BC%6F%B8%80%5E%DE%5D"
engine "pkcs11" set.
Signature Verified Successfully
bash-4.2# echo $?
1
```
Then I modified the input file `in.txt` to force the signature verification to fail and run:
```
bash-4.2# openssl pkeyutl -engine pkcs11 -verify -sigfile sig.bin -in in.txt -pubin -keyform engine -inkey "pkcs11:token=softhsm;object=test;type=public;id=%08%07%EF%5E%7C%B1%BE%1B%2A%7D%A5%B5%65%9C%BC%6F%B8%80%5E%DE%5D"
engine "pkcs11" set.
Signature Verification Failure
bash-4.2# echo $?
1
```
The packages I used:
```
bash-4.2# rpm -q openssl
openssl-1.0.2k-19.amzn2.0.6.x86_64
bash-4.2# rpm -q softhsm
softhsm-2.1.0-2.amzn2.0.2.x86_64
```

**Comment by ozbenh** [comment] 2021-05-12 22:20
Interesting. We should dig to figure out if it's a bug in openssl 1.0.2k (or a patch AL carries) that we need to fix (backport) or whether this is expected in 1.0.x.

**Comment by mtrojnar** [comment] 2022-05-10 17:27
Supporting issues with OpenSSL 1.0.2k is out of scope for project.

**Closed by mtrojnar** 2022-05-10 17:27 UTC
