### ISSUE TITLE
PIN login doesn't work. Stumped.

### ISSUE THREAD

**Issue by asmjmisc** [OpenSC/libp11#237] opened 2018-08-20 10:23 UTC
Hi,

I've embarked on writing a piece of signing software using PKCS#11 smart cards. I haven't gotten far, because, for some reason unknown to me, I cannot log into the card with a PIN.

For comparison, I've tried different cards and different software (for the cards, I have a Gemalto chip card and a Nitrokey Pro) and the software is 1) custom software that works with the Gemalto cards I have, 2) Nitrokey's application and 3) the example auth.c program under examples in the repository.

I can log into the Gemalto card using the custom application and into the Nitrokey using their application. However, logging into both of the cards does not appear to work with the auth.c program nor the quick-n-dirties I put together myself.

I know this isn't exactly a support forum, but my knowledge of smart cards and the whole stack is limited, and I'm sort of stumped here for how to debug this. Am I tripping up on something common and known, or should this be working?

auth.c comes from the current master branch (

**Comment by mtrojnar** [comment] 2018-08-20 10:32
This is a duplicate of #238

**Closed by mtrojnar** 2018-08-20 10:32 UTC
Labels: duplicate
