### ISSUE TITLE
Destroying valid sessions

### ISSUE THREAD

**Issue by commonism** [OpenSC/libp11#8] opened 2013-10-22 06:58 UTC
Trying to access a non existing object results in all sessions to the token getting closed.

https://github.com/OpenSC/libp11/blob/master/src/p11_slot.c#L331

PKCS11_release_all_slots
pkcs11_release_slot
CRYPTOKI_call(ctx, C_CloseAllSessions(priv->id));

Closing only the current session as proposed here https://github.com/commonism/libp11/commit/86a9429b9b8d3b1662b78e45dd956bc52abb3fe6 (part of https://github.com/OpenSC/libp11/pull/7) is proposed therefore.

**Comment by nmav** [comment] 2015-08-26 08:40
The patch isn't really correct. C_CloseAllSessions() closes all sessions in the current slot (not token), which is the expected behavior. Your change doesn't really close anything because you input a slot ID instead of session ID. I'm closing this issue, but feel free to reopen if I have misunderstood it.

**Closed by nmav** 2015-08-26 08:40 UTC
