### ISSUE TITLE
libp11 fails with public key absent

### ISSUE THREAD

**Issue by dwmw2** [OpenSC/libp11#312] opened 2019-10-07 16:58 UTC
Once upon a time, the self tests in http://git.infradead.org/users/dwmw2/openconnect.git/blob/HEAD:/tests/Makefile.am#l193 used to work when built with OpenSSL + libp11.

Now they fail on the token where only private keys were imported without corresponding public keys. 

```
Connecting to obtain cookie (token openconnect-test1 key object=RSA)... SSL connection failure
139951977556608:error:8107A005:PKCS#11 module:pkcs11_private_encrypt:General Error:p11_rsa.c:116:
```

To reproduce, build openconnect with libp11. Run 'make check'

**Comment by dwmw2** [comment] 2019-10-07 17:02
See with 0.4.10 on Fedora 30: https://gitlab.com/openconnect/openconnect/-/jobs/314002609

**Comment by ansasaki** [comment] 2019-11-06 11:10
Is the test trying to negotiate TLS 1.3?
I'm asking because this might be related with OpenSSL's difficulty to generate RSA-PSS signatures using the engine. This problem is caused by the fact that PKCS#11 does not differentiate RSA-PSS keys from RSA keys, but OpenSSL does. If `X509_check_private_key()` is called, then the matching of the key from the device and the public key from the certificate will fail.

**Comment by mtrojnar** [comment] 2020-02-02 23:20
Could this issue be a duplicate of #301?

**Closed** 2022-08-09 07:53 UTC
