### ISSUE TITLE
PKCS11 function C_GetSlotInfo failed 

### ISSUE THREAD

**Issue by draganafcb** [OpenSC/libp11#254] opened 2018-10-04 11:12 UTC
[root@localhost pkcs11]# pkcs11-tool --module=/usr/lib64/pkcs11/libgtop11dotnet.so --list-object
error: PKCS11 function C_GetSlotInfo failed: rv = CKR_TOKEN_NOT_PRESENT (0xe0)

Aborting.
[root@localhost pkcs11]# opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              Gemalto USB Shell Token V2 (539F5EC2) 00 00

[root@localhost pkcs11]# pkcs11-tool --module=/usr/lib64/pkcs11/libgtop11dotnet.so -L
Available slots:
Slot 0 (0x0): Gemalto USB Shell Token V2 (539F5EC2) 00 00
  (empty)
Slot 1 (0x1): empty
  (empty)
Slot 2 (0x2): empty
  (empty)
Slot 3 (0x3): empty
  (empty)
Slot 4 (0x4): empty

**Comment by frankmorgner** [comment] 2018-10-04 11:16
Looks like your vendor's PKCS#11 module doesn't identify your token... You should contact the Gemalto support.

**Comment by draganafcb** [comment] 2018-10-04 11:33
The card is working fine on VirtualBox, but it seems there is a problem when using VMware.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dengert** [comment] 2018-10-04 18:01
This may not be true anymore, but I remember VMWare emulating a generic reader, where as VirtualBox passes the VID (idVendor) and PID (idProduct)  for the usb device. This then allows pcscd  to handle bugs/features of reader specific.   

Do some pcscd debugging  to see if the PID and VID are seen by pcscd. 

Also look at:
 https://ccid.apdu.fr/ccid/supported.html#0x08E60x3438

**Comment by mtrojnar** [comment] 2018-10-04 20:18
Any particular reason this issue was opened in libp11 project?

**Comment by draganafcb** [comment] 2018-10-05 06:14
00000000 debuglog.c:269:DebugLogSetLevel() debug level=debug
00000117 configfile.l:245:DBGetReaderListDir() Parsing conf directory: /etc/read                                                                             er.conf.d
00000011 configfile.l:257:DBGetReaderListDir() Skipping non regular file: .
00000005 configfile.l:257:DBGetReaderListDir() Skipping non regular file: ..
00000009 pcscdaemon.c:525:main() pcsc-lite 1.8.8 daemon ready.
00003393 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x1D6B                                                                             , PID: 0x0001, path: /dev/bus/usb/002/001
00000123 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x1D6B                                                                             , PID: 0x0001, path: /dev/bus/usb/002/001
00000156 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x0E0F                                                                             , PID: 0x0003, path: /dev/bus/usb/002/002
00000120 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x0E0F                                                                             , PID: 0x0003, path: /dev/bus/usb/002/002
00000115 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x1D6B                                                                             , PID: 0x0001, path: /dev/bus/usb/002/001
00000126 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x0E0F                                                                             , PID: 0x0002, path: /dev/bus/usb/002/003
00000124 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x08E6                                                                             , PID: 0x3438, path: /dev/bus/usb/002/004
00000034 hotplug_libudev.c:260:get_driver() Looking for a driver for VID: 0x08E6                                                                             , PID: 0x3438, path: /dev/bus/usb/002/004
00000012 hotplug_libudev.c:312:HPAddDevice() Adding USB device: Gemalto USB Shel                                                                             l Token V2
00000065 readerfactory.c:978:RFInitializeReader() Attempting startup of Gemalto                                                                              USB Shell Token V2 (539F5EC2) 00 00 using /usr/lib64/pcsc/drivers/ifd-ccid.bundl                                                                             e/Contents/Linux/libccid.so
00000245 readerfactory.c:868:RFBindFunctions() Loading IFD Handler 3.0
00000037 ifdhandler.c:1840:init_driver() Driver version: 1.4.10
00000661 ifdhandler.c:1857:init_driver() LogLevel: 0x0003
00000009 ifdhandler.c:1868:init_driver() DriverOptions: 0x0000
00000134 ifdhandler.c:83:CreateChannelByNameOrChannel() Lun: 0, device: usb:08e6                                                                             /3438:libudev:0:/dev/bus/usb/002/004
00000028 ccid_usb.c:258:OpenUSBByName() Using: /usr/lib64/pcsc/drivers/ifd-ccid.                                                                             bundle/Contents/Info.plist
00000552 ccid_usb.c:276:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau                                                                              (ludovic.rousseau@free.fr)
00000009 ccid_usb.c:277:OpenUSBByName() ifdProductString: Generic CCID driver
00000006 ccid_usb.c:278:OpenUSBByName() Copyright: This driver is protected by t                                                                             erms of the GNU Lesser General Public License version 2.1, or (at your option) a                                                                             ny later version.
00003318 ccid_usb.c:551:OpenUSBByName() Found Vendor/Product: 08E6/3438 (Gemalto                                                                              USB Shell Token V2)
00000009 ccid_usb.c:553:OpenUSBByName() Using USB bus/device: 2/4
01914741 ccid_usb.c:1054:get_data_rates() declared: 12903 bps
00000033 ccid_usb.c:1054:get_data_rates() declared: 25806 bps
00000010 ccid_usb.c:1054:get_data_rates() declared: 51613 bps
00000005 ccid_usb.c:1054:get_data_rates() declared: 103226 bps
00000004 ccid_usb.c:1054:get_data_rates() declared: 206452 bps
00000004 ccid_usb.c:1054:get_data_rates() declared: 412903 bps
00000004 ccid_usb.c:1054:get_data_rates() declared: 825806 bps


> This may not be true anymore, but I remember VMWare emulating a generic reader, where as VirtualBox passes the VID (idVendor) and PID (idProduct) for the usb device. This then allows pcscd to handle bugs/features of reader specific.
> 
> Do some pcscd debugging to see if the PID and VID are seen by pcscd.
> 
> Also look at:
> https://ccid.apdu.fr/ccid/supported.html#0x08E60x3438

**Comment by mtrojnar** [comment] 2018-10-08 07:04
Nothing so far indicates that this issue was caused by a bug in libp11.  I'm closing it here.

Please either open an issue with VMware support, Gemalto support, or on https://github.com/OpenSC/OpenSC/issues if you really believe that OpenSC is at fault.

**Closed by mtrojnar** 2018-10-08 07:04 UTC
